### ISSUE TITLE
Will you be at PyCon or EuroPython?

### ISSUE THREAD

**Issue by brainwane** [cenkalti/pypi-notifier#8]
Hi! Thanks for http://pypi-notifier.org/ and for sharing the code!

We're running Python packaging and distribution get-togethers a few times this year -- see https://wiki.python.org/psf/PackagingSprints for more. Will you be at any of them?

Also, https://github.com/pypa/warehouse/blob/master/warehouse/templates/pages/help.html#L174 is the line to change if you want to submit a pull request to change https://pypi.org/help/#project-release-notifications .

Thanks!

**Comment by cenkalti** [comment]
Hello @brainwane,

I will not be at PyCon or EuroPython this year.

Thanks for the PR suggestion. I will send one ASAP.
